### ISSUE TITLE
Configuration to DB Connection - Where is it?

### ISSUE THREAD

**Issue by tysonflint** [rzander/cmcollctr#12]
I've used Collection Commander in years past, and it has been a real life saver.  I have not used the tool in a few years, so am no longer familiar how to configure it to talk to my site server's SQL DB.

In the older version, this was done under the "Options" in the upper-right corner of the window.
In the newer version of Collection Commander, where do you configure:

- SQL Server
- SQL DB Name

![image](https://user-images.githubusercontent.com/1578227/69291201-4901d900-0bb7-11ea-83ea-37b6b625d20e.png)

I downloaded the repo and see what appears to be something like an ODBC connection string within lines 11-13 of this file:
cmcollctr-master\source\CMCollCtr\App.Config

The parameters are as follows:

- data source=
- initial catalog=
- persist security info=True;
- user id=
- password=

Are the above configurable from within the GUI?  Is this an ODBC connection?

I'm running ConfigMgr 2012 on a Server 2016 machine.

Please let me know where I can configure the SQL DB connection.

Thanks again for the great tool!

-=Tyson Flint

**Comment by rzander** [comment]
The current version does not need any connection to the database. Just register the right-click extension (restart the Console to get the Extension) or copy/paste device from the ConfigMgr Console or Excel or ....
