### ISSUE TITLE
Client Center context menu option is greyed out on 64bit Windows with Client Center 1.0.4.2

### ISSUE THREAD

**Issue by gunther3613** [rzander/cmcollctr#2]
The context menu option for opening computer in Client Center is greyed out on 64bit systems with Client Center 1.0.4.2. This is caused by the Client Center Automation Library (latest) referencing the location as "%ProgramFiles%\Client Center for Configuration Manager\SCCMCliCtrWPF.exe". 

Collection Commander is built as 32bit application by default from source and Client Center 1.0.4.2 is built as 64bit . This results in %ProgramFiles% expanded to Program Files (x86)\ for collection Collection Commander on 64bit Windows but Client Center 1.0.4.2 is installed in Program Files\ on 64bit Windows.

**Comment by gunther3613** [comment]
I have tested a 64 bit executable and it works correctly (Client Center not greyed out) due to %ProgramFiles% resolves to Program Files\ in a 64bit process on 64bit Windows.

**Comment by rzander** [comment]
There is an updated ClientCenter Plugin available on : https://github.com/rzander/cmcollctr/releases/download/1.1.0.4/plugin.collctr.sccmclictr.zip

I think this should fix the x86/x64 Issue… ?!

**Comment by gunther3613** [comment]
The updated ClientCenter plugin does work but you have remember to unblock it to get to work. Could you push the changes from the plugin to master so that it is available to everyone when building?

**Comment by rzander** [comment]
I just check my code and I do not have a newer version than the one on GitHub... It sounds that the plugin created from the Code will not work ?

**Comment by gunther3613** [comment]
If I remember correctly yes. I had to figure how the code was called to debug and find that it does references %ProgramFiles%. See second half of first comment. I couldn't verify by rebuilding now because the whole context menu breaks on the Windows 10 insider preview build I am running now.

I have been test using a 64bit build at work everyday for about 2.5 weeks and seems stable. I have occasional issues of machines not showing as connected but there are in another building with a lot of user traffic.

**Comment by gunther3613** [comment]
I see you released a new version. I will test tomorrow at work to see if this is fixed.

**Comment by DwightGappa** [comment]
Tested Collection Commander V1.1.0.5 on 64bit Windows and is working as expected
